In [27]:
import pandas as pd
from urllib.request import urlretrieve
import numpy as np

In [6]:
df = pd.read_csv('who_suicide_statistics.csv')

In [7]:
df.head()

   country  year     sex          age  suicides_no  population
0  Albania  1985  female  15-24 years          NaN    277900.0
1  Albania  1985  female  25-34 years          NaN    246800.0
2  Albania  1985  female  35-54 years          NaN    267500.0
3  Albania  1985  female   5-14 years          NaN    298300.0
4  Albania  1985  female  55-74 years          NaN    138700.0

In [8]:
df['suicides_no'] = df['suicides_no'].fillna(0)

In [9]:
df.head()

   country  year     sex          age  suicides_no  population
0  Albania  1985  female  15-24 years          0.0    277900.0
1  Albania  1985  female  25-34 years          0.0    246800.0
2  Albania  1985  female  35-54 years          0.0    267500.0
3  Albania  1985  female   5-14 years          0.0    298300.0
4  Albania  1985  female  55-74 years          0.0    138700.0

In [10]:
print('The number of unique countries: ', df['country'].nunique())

The number of unique countries:  141

In [11]:
print('The number of unique years: ', df['year'].nunique())

The number of unique years:  38

In [12]:
df.sex.unique()

array(['female', 'male'], dtype=object)

In [13]:
df.sex.value_counts()

sex
female    21888
male      21888
Name: count, dtype: int64

In [14]:
df.groupby('age')['sex'].value_counts()

age          sex
15-24 years  female    3648
             male      3648
25-34 years  female    3648
             male      3648
35-54 years  female    3648
             male      3648
5-14 years   female    3648
             male      3648
55-74 years  female    3648
             male      3648
75+ years    female    3648
             male      3648
Name: count, dtype: int64

In [17]:
df[df['population'] == df['population'].min()]

,country,year,sex,age,suicides_no,population,277900.0,246800.0,267500.0,298300.0,...,12160.0,16577.0,6985.0,2039.0,12065.0,12984.0,17137.0,7428.0,2867.0,13265.0
32351,Rodrigues,2004,male,75+ years,0.0,259.0,259.0,259.0,259.0,259.0,...,259.0,259.0,259.0,259.0,259.0,259.0,259.0,259.0,259.0,259.0

In [18]:
df[df['population']==df['population'].min()]

,country,year,sex,age,suicides_no,population,277900.0,246800.0,267500.0,298300.0,...,12160.0,16577.0,6985.0,2039.0,12065.0,12984.0,17137.0,7428.0,2867.0,13265.0
32351,Rodrigues,2004,male,75+ years,0.0,259.0,259.0,259.0,259.0,259.0,...,259.0,259.0,259.0,259.0,259.0,259.0,259.0,259.0,259.0,259.0

In [30]:
df = pd.read_csv('Shopping_Data.csv')

In [31]:
df.head()

,Customer ID,Age,Gender,Annual Income,Spending Score
0,d410ea53-6661-42a9-ad3a-f554b05fd2a7,30,Male,151479,89
1,1770b26f-493f-46b6-837f-4237fb5a314e,58,Female,185088,95
2,e81aa8eb-1767-4b77-87ce-1620dc732c5e,62,Female,70912,76
3,9795712a-ad19-47bf-8886-4f997d6046e3,23,Male,55460,57
4,64139426-2226-4cd6-bf09-91bce4b4db5e,24,Male,153752,76

In [32]:
df["Age_Bins"] = pd.cut(
    x=df["Age"],
    bins=[1, 19, 29, 39, 49, 59, np.inf],
    labels=["Teenager", "20s", "30s", "40s", "50s", "Senior"],
)

In [33]:
df.head()

,Customer ID,Age,Gender,Annual Income,Spending Score,Age_Bins
0,d410ea53-6661-42a9-ad3a-f554b05fd2a7,30,Male,151479,89,30s
1,1770b26f-493f-46b6-837f-4237fb5a314e,58,Female,185088,95,50s
2,e81aa8eb-1767-4b77-87ce-1620dc732c5e,62,Female,70912,76,Senior
3,9795712a-ad19-47bf-8886-4f997d6046e3,23,Male,55460,57,20s
4,64139426-2226-4cd6-bf09-91bce4b4db5e,24,Male,153752,76,20s

In [35]:
df.groupby("Age_Bins").Spending Score.agg

/var/folders/nk/9q915xx91w7cb2tc87fcl2tw0000gn/T/ipykernel_12263/3046184624.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Age_Bins").sum("Spending Score")

             Age  Annual Income  Spending Score
Age_Bins
Teenager    7482       45499782           21025
20s        49686      224301035          103498
30s        72295      227132413          105496
40s        89113      217439666          101718
50s       114586      231968285          106697
Senior    483993      708471715          324437